### ISSUE TITLE
Introduction question bug

### ISSUE THREAD

**Issue by lilianhj** [jonmcalder/Regular_Expressions#1]
Hi, there seems to be a problem with one of the questions in the introductory lesson (the 'pattern = "I";pattern = "I^"; pattern = "^I"' one) where none of the options register as correct. I was wondering if it might be an issue with my installation, or with the lesson itself? Thanks for writing these lessons!

**Comment by jonmcalder** [comment]
Hi. Thanks very much for raising this issue. Apologies, this was a small bug in the lesson - not sure how I missed it in testing, but I have fixed it now.

You might need to uninstall the course with `uninstall_course("Regular Expressions")` before re-installing to get the update.

Please feel free to open more issues for any further problems you encounter (or to offer suggestions for improvement). I hope the lessons are useful for you!
